import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./hooks/useAuth";
import { NextIntlClientProvider } from "next-intl";
import { ThemeProvider } from "./providers/theme-provider";
import { QueryProvider } from "./providers/QueryProvider";
import AppShell from "./components/AppShell";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "GYM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
    <body className={`${inter.variable} antialiased flex min-h-screen flex-col bg-background`}>
      <ThemeProvider>
        <NextIntlClientProvider>
          <AuthProvider>
            <QueryProvider>
              <AppShell modal={modal}>{children}</AppShell>
            </QueryProvider>
          </AuthProvider>
        </NextIntlClientProvider>
      </ThemeProvider>
    </body>
  </html>
  );
}
