import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import { Sidebar } from "./ui/sidebar/sidebar";
import { AuthProvider } from "./hooks/useAuth";
import { NextIntlClientProvider } from "next-intl";

const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "GYM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  auth,
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ubuntu.variable} antialiased flex`}>
        <NextIntlClientProvider>
          <AuthProvider>
            <Sidebar />
            <main className="p-4 flex-1">{children}</main>
            {auth}
          </AuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
