import type { Metadata } from 'next'
import { Inter } from "next/font/google";
import "./globals.css";
import { BottomNav } from "./ui/bottomNav";
import { AuthProvider } from "./hooks/useAuth";
import { NextIntlClientProvider } from "next-intl";

const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-inter"
});

export const metadata: Metadata = {
  title: "GYM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.variable} antialiased flex min-h-screen flex-col bg-background`}>
        <NextIntlClientProvider>
          <AuthProvider>
            <BottomNav />
            <main className="flex-1 overflow-y-auto p-4 pb-24">{children}</main>
            {modal}
          </AuthProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
